 # Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 # SPDX-License-Identifier: MIT-0
 #
 # Permission is hereby granted, free of charge, to any person obtaining a copy of this
 # software and associated documentation files (the "Software"), to deal in the Software
 # without restriction, including without limitation the rights to use, copy, modify,
 # merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
 # permit persons to whom the Software is furnished to do so.
 #
 # THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
 # INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
 # PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 # HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
 # OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
 # SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

import boto3
import json
import time

def lambda_handler(event, context):
    # parse non-compliant trail from Security Hub finding
    noncompliantTrail = str(event['detail']['findings'][0]['Resources'][0]['Details']['Other']['name'])
    # parse account ID from Security Hub finding, will be needed for Key Policy
    accountID = str(event['detail']['findings'][0]['AwsAccountId'])
    
    # import boto3 clients for KMS and CloudTrail
    kms = boto3.client('kms')
    cloudtrail = boto3.client('cloudtrail')

    # create a new KMS CMK to encrypt the non-compliant trail
    try:
        createKey = kms.create_key(
        Description='Generated by Security Hub to remediate CIS 2.7 Ensure CloudTrail logs are encrypted at rest using KMS CMKs',
        KeyUsage='ENCRYPT_DECRYPT',
        Origin='AWS_KMS'
        )
        # save key id as a variable
        cloudtrailKey = str(createKey['KeyMetadata']['KeyId'])
        print("Created Key" + " " + cloudtrailKey)
    except Exception as e:
        print(e)
        print("KMS CMK creation failed")
        raise
        
    # wait 2 seconds for key creation to propogate
    time.sleep(2)

    # attach an alias for easy identification to the key - must always begin with "alias/"
    try:
        createAlias = kms.create_alias(
        AliasName='alias/' + noncompliantTrail + '-CMK',
        TargetKeyId=cloudtrailKey
        )
        print(createAlias)
    except Exception as e:
        print(e)
        print("Failed to create KMS Alias")
        raise
    
    # wait 1 second
    time.sleep(1)

    # policy name for PutKeyPolicy is always "default"
    policyName = 'default'
    # set Key Policy as JSON object
    keyPolicy={
        "Version": "2012-10-17",
        "Id": "Key policy created by CloudTrail",
        "Statement": [
            {
                "Sid": "Enable IAM User Permissions",
                "Effect": "Allow",
                "Principal": {
                    "AWS": [ "arn:aws:iam::" + accountID + ":root" ]
                },
                "Action": "kms:*",
                "Resource": "*"
            },
            {
                "Sid": "Allow CloudTrail to encrypt logs",
                "Effect": "Allow",
                "Principal": {
                    "Service": "cloudtrail.amazonaws.com"
                },
                "Action": "kms:GenerateDataKey*",
                "Resource": "*",
                "Condition": {
                    "StringLike": {
                        "kms:EncryptionContext:aws:cloudtrail:arn": "arn:aws:cloudtrail:*:" + accountID + ":trail/" + noncompliantTrail
                    }
                }
            },
            {
                "Sid": "Allow CloudTrail to describe key",
                "Effect": "Allow",
                "Principal": {
                    "Service": "cloudtrail.amazonaws.com"
                },
                "Action": "kms:DescribeKey",
                "Resource": "*"
            },
            {
                "Sid": "Allow principals in the account to decrypt log files",
                "Effect": "Allow",
                "Principal": {
                    "AWS": "*"
                },
                "Action": [
                    "kms:Decrypt",
                    "kms:ReEncryptFrom"
                ],
                "Resource": "*",
                "Condition": {
                    "StringEquals": {
                        "kms:CallerAccount": accountID
                    },
                    "StringLike": {
                        "kms:EncryptionContext:aws:cloudtrail:arn": "arn:aws:cloudtrail:*:" + accountID + ":trail/" + noncompliantTrail
                    }
                }
            },
            {
                "Sid": "Allow alias creation during setup",
                "Effect": "Allow",
                "Principal": {
                    "AWS": "*"
                },
                "Action": "kms:CreateAlias",
                "Resource": "*",
                "Condition": {
                    "StringEquals": {
                        "kms:CallerAccount": accountID
                    }
                }
            }
        ]
    }
    # attaches above key policy to key
    try:
        attachKeyPolicy = kms.put_key_policy(
            KeyId=cloudtrailKey,
            Policy=json.dumps(keyPolicy),
            PolicyName=policyName
        )
        print(attachKeyPolicy)
    except Exception as e:
        print(e)
        print("Failed to attach key policy to Key:" + " " + cloudtrailKey)

    # update CloudTrail with the new CMK
    try:
        encryptTrail = cloudtrail.update_trail(
        Name=noncompliantTrail,
        KmsKeyId=cloudtrailKey
        )
        print(encryptTrail)
        print("CloudTrail trail" + " " + noncompliantTrail + " " + "has been successfully encrypted!")
    except Exception as e:
        print(e)